name: map_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # This is used to get the network related API calls
  dio: ^5.1.2
  # This is used to log the API calls
  pretty_dio_logger: ^1.3.1
  # This is used for comparison for bloc
  equatable: ^2.0.5
  # This is used for state management
  flutter_bloc: ^8.1.2
  # This is used to create single instance
  get_it: ^7.6.0
  injectable: ^2.1.1
  # This is used for store data locally
  shared_preferences: ^2.1.1
  # This is used to add map in the app
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator:
  build_runner:

flutter:

  uses-material-design: true